### ISSUE TITLE
allow CORS on appengine configuration

### ISSUE THREAD

**Issue by rafa-acioly** [quickcep/api#1]
We need to enable CORS so other sites/people can make requests on our API.

on file [app.yaml](https://github.com/quickcep/api/blob/master/app.yaml) add the lines; on `handlers` key.
```yaml
http_headers:
    Access-Control-Allow-Origin: *
```

https://cloud.google.com/appengine/docs/standard/go/config/appref

**Comment by manangoel99** [comment]
Can I take this up?

**Comment by rafa-acioly** [comment]
Hi @manangoel99, thank you.
